name: Release

on:
  push:
    tags:
      - 'v*'  # Only trigger on tags like v1.2.3
  workflow_dispatch:  # Manual run support

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "GCS.sln"

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Extract version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Restore
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

    - name: Pack
      run: dotnet pack $SOLUTION --configuration $BUILD_CONFIG --no-build -p:PackageVersion=${VERSION}

    - name: Push to NuGet.org
      run: dotnet nuget push ./bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
      env:
        DOTNET_CLI_NO_PROMPT: true

    - name: Upload Package Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./bin/Release/*.nupkg
